### ISSUE TITLE
Overloads for creating a batch getSingle?

### ISSUE THREAD

**Issue by njlr** [cmeeren/BatchIt#7]
Hello, 

I have hit on a scenario where I think that BatchIt can help, but it does not have an appropriate overload. 

Suppose we have a function for fetching a single book by ID:

```fsharp
let tryFetchBook (bookID : string) : Async<Book option> =
  async {
    // ...
  }
```

And also that we cannot create a good batched version (`string array -> Async<(string * Book option) array>`) for whatever reason. 

This cannot be wrapped by the existing BatchIt overloads (I think!), but there is still benefit to having a batch. If multiple concurrent requests come in for the same book, then we would like to only make one fetch for that ID. 

_In other words, BatchIt can prevent multiple in-flight requests for the same data._

Here are the appropriate overloads to support this:

```fsharp
type Batch with
    static member Create(getSingle : 'a -> Async<'b>, waitSize : int) =
      let getBatched (requests : 'a array) =
        requests
        |> Seq.distinct
        |> Seq.map
          (fun request ->
            async {
              let! result = getSingle request

              return request, result
            })
        |> Async.Parallel

      let notFound = Unchecked.defaultof<'b>

      Batch.Create(getBatched, notFound, waitSize)

    static member Create(getSingle : 'extra -> 'a -> Async<'b>, waitSize : int) =
      let getBatched (extra : 'extra) (requests : 'a array) =
        requests
        |> Seq.distinct
        |> Seq.map
          (fun request ->
            async {
              let! result = getSingle extra request

              return request, result
            })
        |> Async.Parallel

      let notFound = Unchecked.defaultof<'b>

      Batch.Create(getBatched, notFound, waitSize)
```

What do you think?

Happy to send a PR

**Comment by cmeeren** [comment]
Thank you for the suggestion.

What you describe is known to me, at least informally, as a "request collapser" (a term I have from [Polly.Contrib.DuplicateRequestCollapser](https://github.com/Polly-Contrib/Polly.Contrib.DuplicateRequestCollapser)). It is often used (as in the case of Polly.Contrib.DuplicateRequestCollapser) to avoid cache stampedes (hence the name `CacheStampedeResilienceStrategy` from that library). In this case, however, you want to use such a feature even in the absence of a cache.

I recognize the validity and usefulness of your need; however, I choose to turn down this request to add this to BatchIt. This is primarily because BatchIt is a small library focused on batching (centered around the `string array -> Async<(string * Book option) array>` version you mention), and I do not want to complicate the API or the implementation with non-batch-related functionality.

**Comment by njlr** [comment]
> Thank you for the suggestion.
> 
> What you describe is known to me, at least informally, as a "request collapser" (a term I have from [Polly.Contrib.DuplicateRequestCollapser](https://github.com/Polly-Contrib/Polly.Contrib.DuplicateRequestCollapser)). It is often used (as in the case of Polly.Contrib.DuplicateRequestCollapser) to avoid cache stampedes (hence the name `CacheStampedeResilienceStrategy` from that library). In this case, however, you want to use such a feature even in the absence of a cache.
> 
> I recognize the validity and usefulness of your need; however, I choose to turn down this request to add this to BatchIt. This is primarily because BatchIt is a small library focused on batching (centered around the `string array -> Async<(string * Book option) array>` version you mention), and I do not want to complicate the API or the implementation with non-batch-related functionality.

Thanks for the links; "request collapser" was the term I needed but didn't know!

Given that BatchIt is typically wrapped by Polly cache, I think it makes sense to use `Polly.Contrib.DuplicateRequestCollapser`.
